name: Pre-Commit

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  precommit-min-version:
    name: Validate with minimum supported version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Detect Terraform version bounds
        id: minmax
        uses: clowdhaus/terraform-min-max@v2.1.0
        with:
          directory: '.'

      - name: Show detected versions
        run: |
          echo "Minimum version: ${{ steps.minmax.outputs.minVersion }}"
          echo "Maximum version: ${{ steps.minmax.outputs.maxVersion }}"

      - name: Run pre-commit (min version)
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.14.0
        with:
          terraform-version: ${{ steps.minmax.outputs.minVersion }}
          args: 'terraform_validate --color=always --show-diff-on-failure --files ./*'

  precommit-max-version:
    name: Validate with maximum supported version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Detect Terraform version bounds
        id: minmax
        uses: clowdhaus/terraform-min-max@v2.1.0
        with:
          directory: '.'

      - name: Show detected versions
        run: |
          echo "Minimum version: ${{ steps.minmax.outputs.minVersion }}"
          echo "Maximum version: ${{ steps.minmax.outputs.maxVersion }}"

      - name: Run pre-commit (max version)
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.14.0
        with:
          terraform-version: ${{ steps.minmax.outputs.maxVersion }}
          args: 'terraform_validate --color=always --show-diff-on-failure --files ./*'
